l10n: Change comma to a dot
nextcloud/polls pull request #2413
Opened 2022-05-08 19:35 UTC by Valdnet

Signed-off-by: Valdnet <47037905+Valdnet@users.noreply.github.com>

2022-05-09 18:13 UTC, dartcafe requested changes
Ah. No. It describes to set the gap between the option and a calendar event in hours. Maybe the comma has to be removed.

2022-05-10 06:49 UTC, Valdnet commented
> Maybe the comma has to be removed.

The conjunction should then be used.

2022-05-11 16:19 UTC, rakekniven commented on src/js/components/Settings/UserSettings/CalendarSettings.vue
> +				{{ t('polls', 'Activate all calendars and search for conflicting events.') }}
Change requested:
Activate all calendars to search for conflicting events

2022-05-12 16:28 UTC, rakekniven submitted a review, later dismissed

2022-05-14 08:47 UTC, dartcafe requested changes

2022-05-14 08:47 UTC, dartcafe commented on src/js/components/Settings/UserSettings/CalendarSettings.vue
> +				{{ t('polls', 'Set the time interval in hours. A calendar event, whose time interval is set in number of hours, must finish before the given date in order to be included in the conflict check.')
Let's use this: 
'Specify in which period (in hours) before the option existing appointments should be included in the search results.'

2022-05-14 08:47 UTC, dartcafe commented on src/js/components/Settings/UserSettings/CalendarSettings.vue
> +				{{ t('polls', 'Set the time interval in hours. A calendar event, whose time interval is set in number of hours, must start after the given date in order to be included in the conflict check.') }}
And: 
'Specify in which period (in hours) before the option existing appointments should be included in the search results.'

2022-05-16 15:31 UTC, rakekniven submitted a review, later dismissed

2022-05-17 17:00 UTC, dartcafe requested changes

2022-05-17 17:00 UTC, dartcafe commented on src/js/components/Settings/UserSettings/CalendarSettings.vue
> +				{{ t('polls', 'Specify in which period (in hours) before the option existing appointments should be included in the search results.') }}
should be `after` here. ;-)

2022-05-19 18:38 UTC, dartcafe approved these changes

2022-05-19 18:38 UTC, merged

2022-05-19 18:38 UTC, dartcafe commented
finally. 🎉 😄